export const defaultTargets = [
    { desc: 'ingestion api dash', url: 'https://dash.corp.google.com/malachite.ingestion-private-api' },
    { desc: 'controller dash', url: 'https://dash.corp.google.com/malachite.ingestion-controller' },
    { desc: 'normalizer dash', url: 'https://dash.corp.google.com/malachite.ingestion-normalizer' },
    { desc: 'labeler dash', url: 'https://dash.corp.google.com/malachite.ingestion-labeler' },
    { desc: 'oob dash', url: 'https://dash.corp.google.com/malachite.ingestion-outofband-processor' },
    { desc: 'gopher dash', url: 'https://dash.corp.google.com/malachite.ingestion-gopher' },
    { desc: 'ingestion api rollout', url: 'https://rollouts.corp.google.com/rollouts/versions?scope-value=malachite%3Eingestion-private-api&scope-type=project' },
    { desc: 'ingestion api rapid', url: 'https://rapid.corp.google.com/malachite.ingestion-private-api' },
    { desc: 'ingestion api logs prod', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-private-api&job=prod.ingestion-private-api' },
    { desc: 'ingestion api logs prod-asia-south1', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-private-api&job=prod-asia-south1.ingestion-private-api' },
    { desc: 'ingestion api logs prod-asia-southeast1', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-private-api&job=prod-asia-southeast1.ingestion-private-api' },
    { desc: 'ingestion api logs prod-australia-southeast1', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-private-api&job=prod-australia-southeast1.ingestion-private-api' },
    { desc: 'ingestion api logs prod-europe', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-private-api&job=prod-europe.ingestion-private-api' },
    { desc: 'ingestion api logs prod-europe-west2', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-private-api&job=prod-europe-west2.ingestion-private-api' },
    { desc: 'ingestion api logs prod-europe-west3', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-private-api&job=prod-europe-west3.ingestion-private-api' },
    { desc: 'ingestion api logs prod-europe-west6', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-private-api&job=prod-europe-west6.ingestion-private-api' },
    { desc: 'ingestion api logs prod-govcloud-us', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-private-api&job=prod-govcloud-us.ingestion-private-api' },
    { desc: 'ingestion api logs prod-me-central2', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-private-api&job=prod-me-central2.ingestion-private-api' },
    { desc: 'ingestion api logs prod-me-west1', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-private-api&job=prod-me-west1.ingestion-private-api' },
    { desc: 'ingestion api logs canary', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-private-api&job=canary.ingestion-private-api' },
    { desc: 'ingestion api logs dev', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-private-api&job=dev.ingestion-private-api' },
    { desc: 'ingestion api logs staging-loadtest', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-private-api&job=staging-loadtest.ingestion-private-api' },
    { desc: 'ingestion api metrics prod', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-private-api)&borg_job=prod.ingestion-private-api' },
    { desc: 'ingestion api metrics prod-asia-south1', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-private-api)&borg_job=prod-asia-south1.ingestion-private-api' },
    { desc: 'ingestion api metrics prod-asia-southeast1', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-private-api)&borg_job=prod-asia-southeast1.ingestion-private-api' },
    { desc: 'ingestion api metrics prod-australia-southeast1', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-private-api)&borg_job=prod-australia-southeast1.ingestion-private-api' },
    { desc: 'ingestion api metrics prod-europe', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-private-api)&borg_job=prod-europe.ingestion-private-api' },
    { desc: 'ingestion api metrics prod-europe-west2', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-private-api)&borg_job=prod-europe-west2.ingestion-private-api' },
    { desc: 'ingestion api metrics prod-europe-west3', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-private-api)&borg_job=prod-europe-west3.ingestion-private-api' },
    { desc: 'ingestion api metrics prod-europe-west6', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-private-api)&borg_job=prod-europe-west6.ingestion-private-api' },
    { desc: 'ingestion api metrics prod-govcloud-us', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-private-api)&borg_job=prod-govcloud-us.ingestion-private-api' },
    { desc: 'ingestion api metrics prod-me-central2', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-private-api)&borg_job=prod-me-central2.ingestion-private-api' },
    { desc: 'ingestion api metrics prod-me-west1', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-private-api)&borg_job=prod-me-west1.ingestion-private-api' },
    { desc: 'ingestion api metrics canary', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-private-api)&borg_job=canary.ingestion-private-api' },
    { desc: 'ingestion api metrics dev', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-private-api)&borg_job=dev.ingestion-private-api' },
    { desc: 'ingestion api metrics staging-loadtest', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-private-api)&borg_job=staging-loadtest.ingestion-private-api' },
    { desc: 'ingestion api sigma prod', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-private-api/prod.ingestion-private-api' },
    { desc: 'ingestion api sigma prod-asia-south1', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-private-api/prod-asia-south1.ingestion-private-api' },
    { desc: 'ingestion api sigma prod-asia-southeast1', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-private-api/prod-asia-southeast1.ingestion-private-api' },
    { desc: 'ingestion api sigma prod-australia-southeast1', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-private-api/prod-australia-southeast1.ingestion-private-api' },
    { desc: 'ingestion api sigma prod-europe', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-private-api/prod-europe.ingestion-private-api' },
    { desc: 'ingestion api sigma prod-europe-west2', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-private-api/prod-europe-west2.ingestion-private-api' },
    { desc: 'ingestion api sigma prod-europe-west3', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-private-api/prod-europe-west3.ingestion-private-api' },
    { desc: 'ingestion api sigma prod-europe-west6', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-private-api/prod-europe-west6.ingestion-private-api' },
    { desc: 'ingestion api sigma prod-govcloud-us', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-private-api/prod-govcloud-us.ingestion-private-api' },
    { desc: 'ingestion api sigma prod-me-central2', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-private-api/prod-me-central2.ingestion-private-api' },
    { desc: 'ingestion api sigma prod-me-west1', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-private-api/prod-me-west1.ingestion-private-api' },
    { desc: 'ingestion api sigma canary', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-private-api/canary.ingestion-private-api' },
    { desc: 'ingestion api sigma dev', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-private-api/dev.ingestion-private-api' },
    { desc: 'ingestion api sigma staging-loadtest', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-private-api/staging-loadtest.ingestion-private-api' },
    { desc: 'controller rollout', url: 'https://rollouts.corp.google.com/rollouts/versions?scope-value=malachite%3Eingestion-controller&scope-type=project' },
    { desc: 'controller rapid', url: 'https://rapid.corp.google.com/malachite.ingestion-controller' },
    { desc: 'controller logs prod', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-controller&job=prod.ingestion-controller' },
    { desc: 'controller logs prod-asia-south1', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-controller&job=prod-asia-south1.ingestion-controller' },
    { desc: 'controller logs prod-asia-southeast1', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-controller&job=prod-asia-southeast1.ingestion-controller' },
    { desc: 'controller logs prod-australia-southeast1', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-controller&job=prod-australia-southeast1.ingestion-controller' },
    { desc: 'controller logs prod-europe', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-controller&job=prod-europe.ingestion-controller' },
    { desc: 'controller logs prod-europe-west2', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-controller&job=prod-europe-west2.ingestion-controller' },
    { desc: 'controller logs prod-europe-west3', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-controller&job=prod-europe-west3.ingestion-controller' },
    { desc: 'controller logs prod-europe-west6', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-controller&job=prod-europe-west6.ingestion-controller' },
    { desc: 'controller logs prod-govcloud-us', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-controller&job=prod-govcloud-us.ingestion-controller' },
    { desc: 'controller logs prod-me-central2', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-controller&job=prod-me-central2.ingestion-controller' },
    { desc: 'controller logs prod-me-west1', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-controller&job=prod-me-west1.ingestion-controller' },
    { desc: 'controller logs canary', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-controller&job=canary.ingestion-controller' },
    { desc: 'controller logs dev', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-controller&job=dev.ingestion-controller' },
    { desc: 'controller logs staging-loadtest', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-controller&job=staging-loadtest.ingestion-controller' },
    { desc: 'controller metrics prod', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-controller)&borg_job=prod.ingestion-controller' },
    { desc: 'controller metrics prod-asia-south1', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-controller)&borg_job=prod-asia-south1.ingestion-controller' },
    { desc: 'controller metrics prod-asia-southeast1', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-controller)&borg_job=prod-asia-southeast1.ingestion-controller' },
    { desc: 'controller metrics prod-australia-southeast1', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-controller)&borg_job=prod-australia-southeast1.ingestion-controller' },
    { desc: 'controller metrics prod-europe', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-controller)&borg_job=prod-europe.ingestion-controller' },
    { desc: 'controller metrics prod-europe-west2', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-controller)&borg_job=prod-europe-west2.ingestion-controller' },
    { desc: 'controller metrics prod-europe-west3', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-controller)&borg_job=prod-europe-west3.ingestion-controller' },
    { desc: 'controller metrics prod-europe-west6', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-controller)&borg_job=prod-europe-west6.ingestion-controller' },
    { desc: 'controller metrics prod-govcloud-us', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-controller)&borg_job=prod-govcloud-us.ingestion-controller' },
    { desc: 'controller metrics prod-me-central2', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-controller)&borg_job=prod-me-central2.ingestion-controller' },
    { desc: 'controller metrics prod-me-west1', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-controller)&borg_job=prod-me-west1.ingestion-controller' },
    { desc: 'controller metrics canary', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-controller)&borg_job=canary.ingestion-controller' },
    { desc: 'controller metrics dev', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-controller)&borg_job=dev.ingestion-controller' },
    { desc: 'controller metrics staging-loadtest', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-controller)&borg_job=staging-loadtest.ingestion-controller' },
    { desc: 'controller sigma prod', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-controller/prod.ingestion-controller' },
    { desc: 'controller sigma prod-asia-south1', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-controller/prod-asia-south1.ingestion-controller' },
    { desc: 'controller sigma prod-asia-southeast1', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-controller/prod-asia-southeast1.ingestion-controller' },
    { desc: 'controller sigma prod-australia-southeast1', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-controller/prod-australia-southeast1.ingestion-controller' },
    { desc: 'controller sigma prod-europe', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-controller/prod-europe.ingestion-controller' },
    { desc: 'controller sigma prod-europe-west2', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-controller/prod-europe-west2.ingestion-controller' },
    { desc: 'controller sigma prod-europe-west3', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-controller/prod-europe-west3.ingestion-controller' },
    { desc: 'controller sigma prod-europe-west6', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-controller/prod-europe-west6.ingestion-controller' },
    { desc: 'controller sigma prod-govcloud-us', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-controller/prod-govcloud-us.ingestion-controller' },
    { desc: 'controller sigma prod-me-central2', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-controller/prod-me-central2.ingestion-controller' },
    { desc: 'controller sigma prod-me-west1', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-controller/prod-me-west1.ingestion-controller' },
    { desc: 'controller sigma canary', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-controller/canary.ingestion-controller' },
    { desc: 'controller sigma dev', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-controller/dev.ingestion-controller' },
    { desc: 'controller sigma staging-loadtest', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-controller/staging-loadtest.ingestion-controller' },
    { desc: 'normalizer rollout', url: 'https://rollouts.corp.google.com/rollouts/versions?scope-value=malachite%3Eingestion-normalizer&scope-type=project' },
    { desc: 'normalizer rapid', url: 'https://rapid.corp.google.com/malachite.ingestion-normalizer' },
    { desc: 'normalizer logs prod', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-normalizer&job=prod.ingestion-normalizer' },
    { desc: 'normalizer logs prod-asia-south1', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-normalizer&job=prod-asia-south1.ingestion-normalizer' },
    { desc: 'normalizer logs prod-asia-southeast1', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-normalizer&job=prod-asia-southeast1.ingestion-normalizer' },
    { desc: 'normalizer logs prod-australia-southeast1', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-normalizer&job=prod-australia-southeast1.ingestion-normalizer' },
    { desc: 'normalizer logs prod-europe', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-normalizer&job=prod-europe.ingestion-normalizer' },
    { desc: 'normalizer logs prod-europe-west2', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-normalizer&job=prod-europe-west2.ingestion-normalizer' },
    { desc: 'normalizer logs prod-europe-west3', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-normalizer&job=prod-europe-west3.ingestion-normalizer' },
    { desc: 'normalizer logs prod-europe-west6', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-normalizer&job=prod-europe-west6.ingestion-normalizer' },
    { desc: 'normalizer logs prod-govcloud-us', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-normalizer&job=prod-govcloud-us.ingestion-normalizer' },
    { desc: 'normalizer logs prod-me-central2', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-normalizer&job=prod-me-central2.ingestion-normalizer' },
    { desc: 'normalizer logs prod-me-west1', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-normalizer&job=prod-me-west1.ingestion-normalizer' },
    { desc: 'normalizer logs canary', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-normalizer&job=canary.ingestion-normalizer' },
    { desc: 'normalizer logs dev', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-normalizer&job=dev.ingestion-normalizer' },
    { desc: 'normalizer logs staging-loadtest', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-normalizer&job=staging-loadtest.ingestion-normalizer' },
    { desc: 'normalizer metrics prod', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-normalizer)&borg_job=prod.ingestion-normalizer' },
    { desc: 'normalizer metrics prod-asia-south1', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-normalizer)&borg_job=prod-asia-south1.ingestion-normalizer' },
    { desc: 'normalizer metrics prod-asia-southeast1', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-normalizer)&borg_job=prod-asia-southeast1.ingestion-normalizer' },
    { desc: 'normalizer metrics prod-australia-southeast1', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-normalizer)&borg_job=prod-australia-southeast1.ingestion-normalizer' },
    { desc: 'normalizer metrics prod-europe', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-normalizer)&borg_job=prod-europe.ingestion-normalizer' },
    { desc: 'normalizer metrics prod-europe-west2', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-normalizer)&borg_job=prod-europe-west2.ingestion-normalizer' },
    { desc: 'normalizer metrics prod-europe-west3', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-normalizer)&borg_job=prod-europe-west3.ingestion-normalizer' },
    { desc: 'normalizer metrics prod-europe-west6', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-normalizer)&borg_job=prod-europe-west6.ingestion-normalizer' },
    { desc: 'normalizer metrics prod-govcloud-us', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-normalizer)&borg_job=prod-govcloud-us.ingestion-normalizer' },
    { desc: 'normalizer metrics prod-me-central2', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-normalizer)&borg_job=prod-me-central2.ingestion-normalizer' },
    { desc: 'normalizer metrics prod-me-west1', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-normalizer)&borg_job=prod-me-west1.ingestion-normalizer' },
    { desc: 'normalizer metrics canary', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-normalizer)&borg_job=canary.ingestion-normalizer' },
    { desc: 'normalizer metrics dev', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-normalizer)&borg_job=dev.ingestion-normalizer' },
    { desc: 'normalizer metrics staging-loadtest', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-normalizer)&borg_job=staging-loadtest.ingestion-normalizer' },
    { desc: 'normalizer sigma prod', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-normalizer/prod.ingestion-normalizer' },
    { desc: 'normalizer sigma prod-asia-south1', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-normalizer/prod-asia-south1.ingestion-normalizer' },
    { desc: 'normalizer sigma prod-asia-southeast1', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-normalizer/prod-asia-southeast1.ingestion-normalizer' },
    { desc: 'normalizer sigma prod-australia-southeast1', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-normalizer/prod-australia-southeast1.ingestion-normalizer' },
    { desc: 'normalizer sigma prod-europe', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-normalizer/prod-europe.ingestion-normalizer' },
    { desc: 'normalizer sigma prod-europe-west2', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-normalizer/prod-europe-west2.ingestion-normalizer' },
    { desc: 'normalizer sigma prod-europe-west3', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-normalizer/prod-europe-west3.ingestion-normalizer' },
    { desc: 'normalizer sigma prod-europe-west6', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-normalizer/prod-europe-west6.ingestion-normalizer' },
    { desc: 'normalizer sigma prod-govcloud-us', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-normalizer/prod-govcloud-us.ingestion-normalizer' },
    { desc: 'normalizer sigma prod-me-central2', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-normalizer/prod-me-central2.ingestion-normalizer' },
    { desc: 'normalizer sigma prod-me-west1', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-normalizer/prod-me-west1.ingestion-normalizer' },
    { desc: 'normalizer sigma canary', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-normalizer/canary.ingestion-normalizer' },
    { desc: 'normalizer sigma dev', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-normalizer/dev.ingestion-normalizer' },
    { desc: 'normalizer sigma staging-loadtest', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-normalizer/staging-loadtest.ingestion-normalizer' },
    { desc: 'labeler rollout', url: 'https://rollouts.corp.google.com/rollouts/versions?scope-value=malachite%3Eingestion-labeler&scope-type=project' },
    { desc: 'labeler rapid', url: 'https://rapid.corp.google.com/malachite.ingestion-labeler' },
    { desc: 'labeler logs prod', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-labeler&job=prod.ingestion-labeler' },
    { desc: 'labeler logs prod-asia-south1', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-labeler&job=prod-asia-south1.ingestion-labeler' },
    { desc: 'labeler logs prod-asia-southeast1', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-labeler&job=prod-asia-southeast1.ingestion-labeler' },
    { desc: 'labeler logs prod-australia-southeast1', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-labeler&job=prod-australia-southeast1.ingestion-labeler' },
    { desc: 'labeler logs prod-europe', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-labeler&job=prod-europe.ingestion-labeler' },
    { desc: 'labeler logs prod-europe-west2', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-labeler&job=prod-europe-west2.ingestion-labeler' },
    { desc: 'labeler logs prod-europe-west3', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-labeler&job=prod-europe-west3.ingestion-labeler' },
    { desc: 'labeler logs prod-europe-west6', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-labeler&job=prod-europe-west6.ingestion-labeler' },
    { desc: 'labeler logs prod-govcloud-us', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-labeler&job=prod-govcloud-us.ingestion-labeler' },
    { desc: 'labeler logs prod-me-central2', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-labeler&job=prod-me-central2.ingestion-labeler' },
    { desc: 'labeler logs prod-me-west1', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-labeler&job=prod-me-west1.ingestion-labeler' },
    { desc: 'labeler logs canary', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-labeler&job=canary.ingestion-labeler' },
    { desc: 'labeler logs dev', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-labeler&job=dev.ingestion-labeler' },
    { desc: 'labeler logs staging-loadtest', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-labeler&job=staging-loadtest.ingestion-labeler' },
    { desc: 'labeler metrics prod', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-labeler)&borg_job=prod.ingestion-labeler' },
    { desc: 'labeler metrics prod-asia-south1', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-labeler)&borg_job=prod-asia-south1.ingestion-labeler' },
    { desc: 'labeler metrics prod-asia-southeast1', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-labeler)&borg_job=prod-asia-southeast1.ingestion-labeler' },
    { desc: 'labeler metrics prod-australia-southeast1', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-labeler)&borg_job=prod-australia-southeast1.ingestion-labeler' },
    { desc: 'labeler metrics prod-europe', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-labeler)&borg_job=prod-europe.ingestion-labeler' },
    { desc: 'labeler metrics prod-europe-west2', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-labeler)&borg_job=prod-europe-west2.ingestion-labeler' },
    { desc: 'labeler metrics prod-europe-west3', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-labeler)&borg_job=prod-europe-west3.ingestion-labeler' },
    { desc: 'labeler metrics prod-europe-west6', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-labeler)&borg_job=prod-europe-west6.ingestion-labeler' },
    { desc: 'labeler metrics prod-govcloud-us', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-labeler)&borg_job=prod-govcloud-us.ingestion-labeler' },
    { desc: 'labeler metrics prod-me-central2', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-labeler)&borg_job=prod-me-central2.ingestion-labeler' },
    { desc: 'labeler metrics prod-me-west1', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-labeler)&borg_job=prod-me-west1.ingestion-labeler' },
    { desc: 'labeler metrics canary', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-labeler)&borg_job=canary.ingestion-labeler' },
    { desc: 'labeler metrics dev', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-labeler)&borg_job=dev.ingestion-labeler' },
    { desc: 'labeler metrics staging-loadtest', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-labeler)&borg_job=staging-loadtest.ingestion-labeler' },
    { desc: 'labeler sigma prod', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-labeler/prod.ingestion-labeler' },
    { desc: 'labeler sigma prod-asia-south1', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-labeler/prod-asia-south1.ingestion-labeler' },
    { desc: 'labeler sigma prod-asia-southeast1', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-labeler/prod-asia-southeast1.ingestion-labeler' },
    { desc: 'labeler sigma prod-australia-southeast1', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-labeler/prod-australia-southeast1.ingestion-labeler' },
    { desc: 'labeler sigma prod-europe', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-labeler/prod-europe.ingestion-labeler' },
    { desc: 'labeler sigma prod-europe-west2', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-labeler/prod-europe-west2.ingestion-labeler' },
    { desc: 'labeler sigma prod-europe-west3', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-labeler/prod-europe-west3.ingestion-labeler' },
    { desc: 'labeler sigma prod-europe-west6', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-labeler/prod-europe-west6.ingestion-labeler' },
    { desc: 'labeler sigma prod-govcloud-us', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-labeler/prod-govcloud-us.ingestion-labeler' },
    { desc: 'labeler sigma prod-me-central2', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-labeler/prod-me-central2.ingestion-labeler' },
    { desc: 'labeler sigma prod-me-west1', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-labeler/prod-me-west1.ingestion-labeler' },
    { desc: 'labeler sigma canary', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-labeler/canary.ingestion-labeler' },
    { desc: 'labeler sigma dev', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-labeler/dev.ingestion-labeler' },
    { desc: 'labeler sigma staging-loadtest', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-labeler/staging-loadtest.ingestion-labeler' },
    { desc: 'oob rollout', url: 'https://rollouts.corp.google.com/rollouts/versions?scope-value=malachite%3Eingestion-outofband-processor&scope-type=project' },
    { desc: 'oob rapid', url: 'https://rapid.corp.google.com/malachite.ingestion-outofband-processor' },
    { desc: 'oob logs prod', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-outofband-processor&job=prod.ingestion-outofband-processor' },
    { desc: 'oob logs prod-asia-south1', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-outofband-processor&job=prod-asia-south1.ingestion-outofband-processor' },
    { desc: 'oob logs prod-asia-southeast1', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-outofband-processor&job=prod-asia-southeast1.ingestion-outofband-processor' },
    { desc: 'oob logs prod-australia-southeast1', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-outofband-processor&job=prod-australia-southeast1.ingestion-outofband-processor' },
    { desc: 'oob logs prod-europe', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-outofband-processor&job=prod-europe.ingestion-outofband-processor' },
    { desc: 'oob logs prod-europe-west2', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-outofband-processor&job=prod-europe-west2.ingestion-outofband-processor' },
    { desc: 'oob logs prod-europe-west3', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-outofband-processor&job=prod-europe-west3.ingestion-outofband-processor' },
    { desc: 'oob logs prod-europe-west6', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-outofband-processor&job=prod-europe-west6.ingestion-outofband-processor' },
    { desc: 'oob logs prod-govcloud-us', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-outofband-processor&job=prod-govcloud-us.ingestion-outofband-processor' },
    { desc: 'oob logs prod-me-central2', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-outofband-processor&job=prod-me-central2.ingestion-outofband-processor' },
    { desc: 'oob logs prod-me-west1', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-outofband-processor&job=prod-me-west1.ingestion-outofband-processor' },
    { desc: 'oob logs canary', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-outofband-processor&job=canary.ingestion-outofband-processor' },
    { desc: 'oob logs dev', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-outofband-processor&job=dev.ingestion-outofband-processor' },
    { desc: 'oob logs staging-loadtest', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-outofband-processor&job=staging-loadtest.ingestion-outofband-processor' },
    { desc: 'oob metrics prod', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-outofband-processor)&borg_job=prod.ingestion-outofband-processor' },
    { desc: 'oob metrics prod-asia-south1', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-outofband-processor)&borg_job=prod-asia-south1.ingestion-outofband-processor' },
    { desc: 'oob metrics prod-asia-southeast1', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-outofband-processor)&borg_job=prod-asia-southeast1.ingestion-outofband-processor' },
    { desc: 'oob metrics prod-australia-southeast1', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-outofband-processor)&borg_job=prod-australia-southeast1.ingestion-outofband-processor' },
    { desc: 'oob metrics prod-europe', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-outofband-processor)&borg_job=prod-europe.ingestion-outofband-processor' },
    { desc: 'oob metrics prod-europe-west2', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-outofband-processor)&borg_job=prod-europe-west2.ingestion-outofband-processor' },
    { desc: 'oob metrics prod-europe-west3', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-outofband-processor)&borg_job=prod-europe-west3.ingestion-outofband-processor' },
    { desc: 'oob metrics prod-europe-west6', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-outofband-processor)&borg_job=prod-europe-west6.ingestion-outofband-processor' },
    { desc: 'oob metrics prod-govcloud-us', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-outofband-processor)&borg_job=prod-govcloud-us.ingestion-outofband-processor' },
    { desc: 'oob metrics prod-me-central2', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-outofband-processor)&borg_job=prod-me-central2.ingestion-outofband-processor' },
    { desc: 'oob metrics prod-me-west1', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-outofband-processor)&borg_job=prod-me-west1.ingestion-outofband-processor' },
    { desc: 'oob metrics canary', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-outofband-processor)&borg_job=canary.ingestion-outofband-processor' },
    { desc: 'oob metrics dev', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-outofband-processor)&borg_job=dev.ingestion-outofband-processor' },
    { desc: 'oob metrics staging-loadtest', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-outofband-processor)&borg_job=staging-loadtest.ingestion-outofband-processor' },
    { desc: 'oob sigma prod', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-outofband-processor/prod.ingestion-outofband-processor' },
    { desc: 'oob sigma prod-asia-south1', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-outofband-processor/prod-asia-south1.ingestion-outofband-processor' },
    { desc: 'oob sigma prod-asia-southeast1', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-outofband-processor/prod-asia-southeast1.ingestion-outofband-processor' },
    { desc: 'oob sigma prod-australia-southeast1', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-outofband-processor/prod-australia-southeast1.ingestion-outofband-processor' },
    { desc: 'oob sigma prod-europe', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-outofband-processor/prod-europe.ingestion-outofband-processor' },
    { desc: 'oob sigma prod-europe-west2', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-outofband-processor/prod-europe-west2.ingestion-outofband-processor' },
    { desc: 'oob sigma prod-europe-west3', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-outofband-processor/prod-europe-west3.ingestion-outofband-processor' },
    { desc: 'oob sigma prod-europe-west6', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-outofband-processor/prod-europe-west6.ingestion-outofband-processor' },
    { desc: 'oob sigma prod-govcloud-us', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-outofband-processor/prod-govcloud-us.ingestion-outofband-processor' },
    { desc: 'oob sigma prod-me-central2', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-outofband-processor/prod-me-central2.ingestion-outofband-processor' },
    { desc: 'oob sigma prod-me-west1', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-outofband-processor/prod-me-west1.ingestion-outofband-processor' },
    { desc: 'oob sigma canary', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-outofband-processor/canary.ingestion-outofband-processor' },
    { desc: 'oob sigma dev', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-outofband-processor/dev.ingestion-outofband-processor' },
    { desc: 'oob sigma staging-loadtest', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-outofband-processor/staging-loadtest.ingestion-outofband-processor' },
    { desc: 'gopher rollout', url: 'https://rollouts.corp.google.com/rollouts/versions?scope-value=malachite%3Eingestion-gopher&scope-type=project' },
    { desc: 'gopher rapid', url: 'https://rapid.corp.google.com/malachite.ingestion-gopher' },
    { desc: 'gopher logs prod', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-gopher&job=prod.ingestion-gopher' },
    { desc: 'gopher logs prod-asia-south1', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-gopher&job=prod-asia-south1.ingestion-gopher' },
    { desc: 'gopher logs prod-asia-southeast1', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-gopher&job=prod-asia-southeast1.ingestion-gopher' },
    { desc: 'gopher logs prod-australia-southeast1', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-gopher&job=prod-australia-southeast1.ingestion-gopher' },
    { desc: 'gopher logs prod-europe', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-gopher&job=prod-europe.ingestion-gopher' },
    { desc: 'gopher logs prod-europe-west2', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-gopher&job=prod-europe-west2.ingestion-gopher' },
    { desc: 'gopher logs prod-europe-west3', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-gopher&job=prod-europe-west3.ingestion-gopher' },
    { desc: 'gopher logs prod-europe-west6', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-gopher&job=prod-europe-west6.ingestion-gopher' },
    { desc: 'gopher logs prod-govcloud-us', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-gopher&job=prod-govcloud-us.ingestion-gopher' },
    { desc: 'gopher logs prod-me-central2', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-gopher&job=prod-me-central2.ingestion-gopher' },
    { desc: 'gopher logs prod-me-west1', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-gopher&job=prod-me-west1.ingestion-gopher' },
    { desc: 'gopher logs canary', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-gopher&job=canary.ingestion-gopher' },
    { desc: 'gopher logs dev', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-gopher&job=dev.ingestion-gopher' },
    { desc: 'gopher logs staging-loadtest', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-ingestion-gopher&job=staging-loadtest.ingestion-gopher' },
    { desc: 'gopher metrics prod', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-gopher)&borg_job=prod.ingestion-gopher' },
    { desc: 'gopher metrics prod-asia-south1', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-gopher)&borg_job=prod-asia-south1.ingestion-gopher' },
    { desc: 'gopher metrics prod-asia-southeast1', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-gopher)&borg_job=prod-asia-southeast1.ingestion-gopher' },
    { desc: 'gopher metrics prod-australia-southeast1', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-gopher)&borg_job=prod-australia-southeast1.ingestion-gopher' },
    { desc: 'gopher metrics prod-europe', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-gopher)&borg_job=prod-europe.ingestion-gopher' },
    { desc: 'gopher metrics prod-europe-west2', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-gopher)&borg_job=prod-europe-west2.ingestion-gopher' },
    { desc: 'gopher metrics prod-europe-west3', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-gopher)&borg_job=prod-europe-west3.ingestion-gopher' },
    { desc: 'gopher metrics prod-europe-west6', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-gopher)&borg_job=prod-europe-west6.ingestion-gopher' },
    { desc: 'gopher metrics prod-govcloud-us', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-gopher)&borg_job=prod-govcloud-us.ingestion-gopher' },
    { desc: 'gopher metrics prod-me-central2', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-gopher)&borg_job=prod-me-central2.ingestion-gopher' },
    { desc: 'gopher metrics prod-me-west1', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-gopher)&borg_job=prod-me-west1.ingestion-gopher' },
    { desc: 'gopher metrics canary', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-gopher)&borg_job=canary.ingestion-gopher' },
    { desc: 'gopher metrics dev', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-gopher)&borg_job=dev.ingestion-gopher' },
    { desc: 'gopher metrics staging-loadtest', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-ingestion-gopher)&borg_job=staging-loadtest.ingestion-gopher' },
    { desc: 'gopher sigma prod', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-gopher/prod.ingestion-gopher' },
    { desc: 'gopher sigma prod-asia-south1', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-gopher/prod-asia-south1.ingestion-gopher' },
    { desc: 'gopher sigma prod-asia-southeast1', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-gopher/prod-asia-southeast1.ingestion-gopher' },
    { desc: 'gopher sigma prod-australia-southeast1', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-gopher/prod-australia-southeast1.ingestion-gopher' },
    { desc: 'gopher sigma prod-europe', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-gopher/prod-europe.ingestion-gopher' },
    { desc: 'gopher sigma prod-europe-west2', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-gopher/prod-europe-west2.ingestion-gopher' },
    { desc: 'gopher sigma prod-europe-west3', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-gopher/prod-europe-west3.ingestion-gopher' },
    { desc: 'gopher sigma prod-europe-west6', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-gopher/prod-europe-west6.ingestion-gopher' },
    { desc: 'gopher sigma prod-govcloud-us', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-gopher/prod-govcloud-us.ingestion-gopher' },
    { desc: 'gopher sigma prod-me-central2', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-gopher/prod-me-central2.ingestion-gopher' },
    { desc: 'gopher sigma prod-me-west1', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-gopher/prod-me-west1.ingestion-gopher' },
    { desc: 'gopher sigma canary', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-gopher/canary.ingestion-gopher' },
    { desc: 'gopher sigma dev', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-gopher/dev.ingestion-gopher' },
    { desc: 'gopher sigma staging-loadtest', url: 'https://sigma.corp.google.com/jobs/malachite-ingestion-gopher/staging-loadtest.ingestion-gopher' },
    { desc: 'event db dash', url: 'https://dash.corp.google.com/pod-spanner.malachite-event-spanner:malachite.event-spanner' },
    { desc: 'event db metrics prod', url: 'https://span.corp.google.com/db/global/malachite:event' },
    { desc: 'event db metrics prod-asia-south1', url: 'https://span.corp.google.com/db/global/malachite:event-asia-south1' },
    { desc: 'event db metrics prod-asia-southeast1', url: 'https://span.corp.google.com/db/global/malachite:event-asia-southeast1' },
    { desc: 'event db metrics prod-australia-southeast1', url: 'https://span.corp.google.com/db/global/malachite:event-australia-southeast1' },
    { desc: 'event db metrics prod-europe', url: 'https://span.corp.google.com/db/global/malachite:event-europe' },
    { desc: 'event db metrics prod-europe-west2', url: 'https://span.corp.google.com/db/global/malachite:event-europe-west2' },
    { desc: 'event db metrics prod-europe-west3', url: 'https://span.corp.google.com/db/global/malachite:event-europe-west3' },
    { desc: 'event db metrics prod-europe-west6', url: 'https://span.corp.google.com/db/global/malachite:event-europe-west6' },
    { desc: 'event db metrics prod-govcloud-us', url: 'https://span.corp.google.com/db/global/malachite:event-govcloud-us' },
    { desc: 'event db metrics prod-me-central2', url: 'https://span.corp.google.com/db/global/malachite:event-me-central2' },
    { desc: 'event db metrics prod-me-west1', url: 'https://span.corp.google.com/db/global/malachite:event-me-west1' },
    { desc: 'event db metrics canary', url: 'https://span.corp.google.com/db/global/malachite:event-canary' },
    { desc: 'event db metrics dev', url: 'https://span.corp.google.com/db/global/malachite:event-dev' },
    { desc: 'event db metrics staging-loadtest', url: 'https://span.corp.google.com/db/global/malachite:event-staging' },
    { desc: 'customer man rollout', url: 'https://rollouts.corp.google.com/rollouts/versions?scope-value=malachite%3Ecustomer-management&scope-type=project' },
    { desc: 'customer man rapid', url: 'https://rapid.corp.google.com/malachite.customer-management' },
    { desc: 'customer man dash', url: 'https://dash.corp.google.com/malachite.customer-management' },
    { desc: 'customer man logs prod', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-customer-management&job=prod.customer-management' },
    { desc: 'customer man logs prod-asia-south1', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-customer-management&job=prod-asia-south1.customer-management' },
    { desc: 'customer man logs prod-asia-southeast1', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-customer-management&job=prod-asia-southeast1.customer-management' },
    { desc: 'customer man logs prod-australia-southeast1', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-customer-management&job=prod-australia-southeast1.customer-management' },
    { desc: 'customer man logs prod-europe', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-customer-management&job=prod-europe.customer-management' },
    { desc: 'customer man logs prod-europe-west2', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-customer-management&job=prod-europe-west2.customer-management' },
    { desc: 'customer man logs prod-europe-west3', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-customer-management&job=prod-europe-west3.customer-management' },
    { desc: 'customer man logs prod-europe-west6', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-customer-management&job=prod-europe-west6.customer-management' },
    { desc: 'customer man logs prod-govcloud-us', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-customer-management&job=prod-govcloud-us.customer-management' },
    { desc: 'customer man logs prod-me-central2', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-customer-management&job=prod-me-central2.customer-management' },
    { desc: 'customer man logs prod-me-west1', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-customer-management&job=prod-me-west1.customer-management' },
    { desc: 'customer man logs canary', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-customer-management&job=canary.customer-management' },
    { desc: 'customer man logs dev', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-customer-management&job=dev.customer-management' },
    { desc: 'customer man logs staging-loadtest', url: 'https://analog.corp.google.com/viewremote?remote_log_name=/debug/google3-logging&user=malachite-customer-management&job=staging-loadtest.customer-management' },
    { desc: 'customer man metrics prod', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-customer-management)&borg_job=prod.customer-management' },
    { desc: 'customer man metrics prod-asia-south1', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-customer-management)&borg_job=prod-asia-south1.customer-management' },
    { desc: 'customer man metrics prod-asia-southeast1', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-customer-management)&borg_job=prod-asia-southeast1.customer-management' },
    { desc: 'customer man metrics prod-australia-southeast1', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-customer-management)&borg_job=prod-australia-southeast1.customer-management' },
    { desc: 'customer man metrics prod-europe', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-customer-management)&borg_job=prod-europe.customer-management' },
    { desc: 'customer man metrics prod-europe-west2', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-customer-management)&borg_job=prod-europe-west2.customer-management' },
    { desc: 'customer man metrics prod-europe-west3', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-customer-management)&borg_job=prod-europe-west3.customer-management' },
    { desc: 'customer man metrics prod-europe-west6', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-customer-management)&borg_job=prod-europe-west6.customer-management' },
    { desc: 'customer man metrics prod-govcloud-us', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-customer-management)&borg_job=prod-govcloud-us.customer-management' },
    { desc: 'customer man metrics prod-me-central2', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-customer-management)&borg_job=prod-me-central2.customer-management' },
    { desc: 'customer man metrics prod-me-west1', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-customer-management)&borg_job=prod-me-west1.customer-management' },
    { desc: 'customer man metrics canary', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-customer-management)&borg_job=canary.customer-management' },
    { desc: 'customer man metrics dev', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-customer-management)&borg_job=dev.customer-management' },
    { desc: 'customer man metrics staging-loadtest', url: 'https://automon.corp.google.com/dashboard/job?group=(borg_user=malachite-customer-management)&borg_job=staging-loadtest.customer-management' },
    { desc: 'customer man sigma prod', url: 'https://sigma.corp.google.com/jobs/malachite-customer-management/prod.customer-management' },
    { desc: 'customer man sigma prod-asia-south1', url: 'https://sigma.corp.google.com/jobs/malachite-customer-management/prod-asia-south1.customer-management' },
    { desc: 'customer man sigma prod-asia-southeast1', url: 'https://sigma.corp.google.com/jobs/malachite-customer-management/prod-asia-southeast1.customer-management' },
    { desc: 'customer man sigma prod-australia-southeast1', url: 'https://sigma.corp.google.com/jobs/malachite-customer-management/prod-australia-southeast1.customer-management' },
    { desc: 'customer man sigma prod-europe', url: 'https://sigma.corp.google.com/jobs/malachite-customer-management/prod-europe.customer-management' },
    { desc: 'customer man sigma prod-europe-west2', url: 'https://sigma.corp.google.com/jobs/malachite-customer-management/prod-europe-west2.customer-management' },
    { desc: 'customer man sigma prod-europe-west3', url: 'https://sigma.corp.google.com/jobs/malachite-customer-management/prod-europe-west3.customer-management' },
    { desc: 'customer man sigma prod-europe-west6', url: 'https://sigma.corp.google.com/jobs/malachite-customer-management/prod-europe-west6.customer-management' },
    { desc: 'customer man sigma prod-govcloud-us', url: 'https://sigma.corp.google.com/jobs/malachite-customer-management/prod-govcloud-us.customer-management' },
    { desc: 'customer man sigma prod-me-central2', url: 'https://sigma.corp.google.com/jobs/malachite-customer-management/prod-me-central2.customer-management' },
    { desc: 'customer man sigma prod-me-west1', url: 'https://sigma.corp.google.com/jobs/malachite-customer-management/prod-me-west1.customer-management' },
    { desc: 'customer man sigma canary', url: 'https://sigma.corp.google.com/jobs/malachite-customer-management/canary.customer-management' },
    { desc: 'customer man sigma dev', url: 'https://sigma.corp.google.com/jobs/malachite-customer-management/dev.customer-management' },
    { desc: 'customer man sigma staging-loadtest', url: 'https://sigma.corp.google.com/jobs/malachite-customer-management/staging-loadtest.customer-management' },
]